title: Jiheum
description: Jiheum
timezone: Asia/Seoul 

repository: jxheum/jxheum.github.io

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 10
paginate_path: 'blog/:num/'

exclude: [README.md]

github_url:
  username: jxheum
