title: BJH
description: BJH blog
timezone: Asia/Seoul 

repository: jxheum/jxheum.github.io

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 10
paginate_path: '/:num/'

exclude: [README.md]

github_url:
  username: jxheum
