title: Jiheum
description: Jiheum
timezone: Asia/Seoul 

repository: jxheum/jxheum.github.io

permalink: /post/:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: '/:num/'

exclude: [README.md]

github_url:
  username: jxheum

defaults:
  -
    scope:
      path: 'offline.html'
    values:
      sitemap: false